name: Linux AppImage

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
    - '*'

defaults:
  run:
    shell: bash

env:
  SOURCE_DIR:   ${{ github.workspace }}
  QT_VERSION:   6.5.1
  ARTIFACT:     LiniTunes.AppImage
  
jobs:
  build:
    runs-on:  ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Qt
        uses: jurplel/install-qt-action@v3.2.1
        with:
          version:      ${{ env.QT_VERSION }}
          host:         linux
          target:       desktop
          dir:          ${{ runner.temp }}
          modules:      qtcharts qt5compat qtshadertools
          setup-python: true

      - name: Install libimobiledevice
        run: |
          sudo apt-get install \
            build-essential \
            checkinstall \
            git \
            autoconf \
            automake \
            libtool-bin \
            libssl-dev \
            libusb-1.0-0-dev \
            udev
          
          sudo apt-get install \
          	doxygen
          
          git clone https://github.com/libimobiledevice/libplist
          cd libplist
          ./autogen.sh
          make
          sudo make install
          cd ..
          
          git clone https://github.com/libimobiledevice/libimobiledevice-glue
          cd libimobiledevice-glue
          ./autogen.sh
          make
          sudo make install
          cd ..
          
          git clone https://github.com/libimobiledevice/libusbmuxd.git
          cd libusbmuxd
          ./autogen.sh
          make
          sudo make install
          cd ..
          
          git clone https://github.com/libimobiledevice/libimobiledevice.git
          cd libimobiledevice
          ./autogen.sh --without-cython
          make
          sudo make install
          cd ..
          
          git clone https://github.com/libimobiledevice/usbmuxd.git
          cd usbmuxd
          ./autogen.sh
          make
          sudo make install
          cd ..

      - name: Install AppImage dependencies
        run: sudo apt-get install -y fuse libfuse2 libxcb-cursor0

      - name: Create build directory
        run:  mkdir ${{ env.SOURCE_DIR }}/build

      - name: Build
        working-directory: ${{ env.SOURCE_DIR }}/build
        run:  |
              ${{ runner.temp }}/Qt/${{ env.QT_VERSION }}/gcc_64/bin/qt-cmake ${{ env.SOURCE_DIR }}/LiniTunes/CMakeLists.txt
              make -j2

      - name: AppImage
        working-directory: ${{ env.SOURCE_DIR }}/build
        run: |
          wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          wget https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage
          chmod +x linuxdeploy*.AppImage
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$${{ runner.temp }}/Qt/6.5.1/gcc_64/lib/:/usr/lib/
          export QMAKE=${{ runner.temp }}/Qt/6.5.1/gcc_64/bin/qmake
          export QML_SOURCES_PATHS=${{ env.SOURCE_DIR }}/LiniTunes/
          ./linuxdeploy-x86_64.AppImage --appdir AppDir -e LiniTunes -i ${{ env.SOURCE_DIR }}/LiniTunes/images/linitunes.png -d ${{ env.SOURCE_DIR }}/linux/linitunes.desktop --plugin qt -l libusbmuxd-2.0.so  --output appimage
          mv LiniTunes*.AppImage ${{ env.ARTIFACT }} 

      - name: Linux artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ env.ARTIFACT }}
          path: ${{ env.SOURCE_DIR }}/build/${{ env.ARTIFACT }}
