name: Linux AppImage

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
    - '*'

defaults:
  run:
    shell: bash

env:
  SOURCE_DIR:   ${{ github.workspace }}
  QT_VERSION:   6.5.*
  ARTIFACT:     LiniTunes.AppImage
  
jobs:
  build:
    runs-on:  ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Qt
        uses: jurplel/install-qt-action@v3.2.1
        with:
          version:      ${{ env.QT_VERSION }}
          host:         linux
          target:       desktop
          dir:          ${{ runner.temp }}
          modules:      qtcharts qt5compat qtshadertools
          setup-python: true

      - name: Install libimobiledevice with dpkg
        run:  sudo apt-get install -y libimobiledevice6 usbmuxd libimobiledevice-utils libimobiledevice-dev

      - name: Install AppImage dependencies
        run: sudo apt-get install -y fuse libfuse2 libxcb-cursor0

      - name: Create build directory
        run:  mkdir ${{ env.SOURCE_DIR }}/build

      - name: Build
        working-directory: ${{ env.SOURCE_DIR }}/build
        run:  |
              ${{ runner.temp }}/Qt/${{ env.QT_VERSION }}/gcc_64/bin/qmake ${{ env.SOURCE_DIR }}/LiniTunes/LiniTunes.pro -spec linux-g++ CONFIG+=qtquickcompiler && /usr/bin/make qmake_all
              make -j2

      - name: AppImage
        working-directory: ${{ env.SOURCE_DIR }}/build
        run: |
          wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          wget https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage
          chmod +x linuxdeploy*.AppImage
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$${{ runner.temp }}/Qt/6.5.1/gcc_64/lib/:/usr/lib/
          export QMAKE=${{ runner.temp }}/Qt/6.5.1/gcc_64/bin/qmake
          export QML_SOURCES_PATHS=${{ env.SOURCE_DIR }}/LiniTunes/
          ./linuxdeploy-x86_64.AppImage --appdir AppDir -e LiniTunes -i ${{ env.SOURCE_DIR }}/LiniTunes/images/linitunes.png -d ${{ env.SOURCE_DIR }}/linux/linitunes.desktop --plugin qt --output appimage
          mv LiniTunes*.AppImage ${{ env.ARTIFACT }} 

      - name: Linux artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ env.ARTIFACT }}
          path: ${{ env.SOURCE_DIR }}/build/${{ env.ARTIFACT }}
